@echo off
REM SPDX-License-Identifier: GPL-3.0-or-later
REM Copyright (c) 2023-2026 Dismo Industries LLC
REM Build CyberFidget WASM for the browser emulator (Windows).
REM
REM Prerequisites: Emscripten SDK
REM   emsdk install 3.1.51
REM   emsdk activate 3.1.51
REM   call emsdk_env.bat
REM
REM Usage:
REM   build_wasm.bat
REM     → Build default demo (output: build\cyberfidget.js, build\cyberfidget.wasm)
REM
REM   build_wasm.bat MyApp.h MyApp.cpp
REM     → Build custom app (copies files to wasm\app\, builds with WASM_APP=Custom)
REM
REM After building, copy build\cyberfidget.js and build\cyberfidget.wasm to the
REM website's wasm\ directory.

setlocal
cd /d "%~dp0"
set "APP_DIR=%~dp0app"
set "BUILD_DIR=%~dp0build"

where emcc >nul 2>nul
if errorlevel 1 (
    echo Emscripten not found. Install and activate the SDK, then run emsdk_env.bat
    echo   https://emscripten.org/docs/getting_started/downloads.html
    exit /b 1
)

if "%~1"=="" goto build_demo
if "%~2"=="" (
    echo Usage: %~nx0 [AppName.h AppName.cpp]
    echo   No args: build default demo
    echo   Two args: build custom app
    exit /b 1
)

set "H_FILE=%~1"
set "CPP_FILE=%~2"
if not exist "%H_FILE%" (
    echo Error: %H_FILE% not found
    exit /b 1
)
if not exist "%CPP_FILE%" (
    echo Error: %CPP_FILE% not found
    exit /b 1
)

REM Get app name from header (e.g. MyApp.h -> MyApp)
for %%F in ("%H_FILE%") do set "BASE_H=%%~nxF"
for %%F in ("%BASE_H%") do set "APP_NAME=%%~nF"

if not exist "%APP_DIR%" mkdir "%APP_DIR%"
copy /Y "%H_FILE%" "%APP_DIR%\%APP_NAME%.h" >nul
copy /Y "%CPP_FILE%" "%APP_DIR%\%APP_NAME%.cpp" >nul

REM Generate app_include.h
echo // Generated by build_wasm.bat - do not edit > "%APP_DIR%\app_include.h"
echo #include "App.h" >> "%APP_DIR%\app_include.h"
echo #include "%APP_NAME%.h" >> "%APP_DIR%\app_include.h"

echo === Building custom WASM app: %APP_NAME% ===
goto run_cmake

:build_demo
echo === Building default WASM demo ===

:run_cmake
if not exist "%BUILD_DIR%" mkdir "%BUILD_DIR%"
cd /d "%BUILD_DIR%"

if "%~1"=="" (
    call emcmake cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
) else (
    call emcmake cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DWASM_APP=Custom -DCUSTOM_APP_NAME=%APP_NAME%
)
if errorlevel 1 (
    echo ERROR: cmake failed
    exit /b 1
)

call emmake ninja
if errorlevel 1 (
    echo ERROR: Build failed
    exit /b 1
)

echo.
echo Done. Output: build\cyberfidget.js, build\cyberfidget.wasm
echo Copy to the website's wasm\ directory.
exit /b 0
