#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2023-2026 Dismo Industries LLC
# Build CyberFidget WASM for the browser emulator.
#
# Prerequisites: Emscripten SDK
#   git clone https://github.com/emscripten-core/emsdk.git && cd emsdk
#   ./emsdk install 3.1.51 && ./emsdk activate 3.1.51
#   source ./emsdk_env.sh
#
# Usage:
#   ./build_wasm.sh
#     → Build default demo (output: build/cyberfidget.js, build/cyberfidget.wasm)
#
#   ./build_wasm.sh MyApp.h MyApp.cpp
#     → Build custom app (copies files to wasm/app/, builds with WASM_APP=Custom)
#     → Output: build/cyberfidget.js, build/cyberfidget.wasm (use in website or drag .wasm)
#
# After building, copy build/cyberfidget.js and build/cyberfidget.wasm to the
# website's wasm/ directory, or use the website's "Load from File" if available.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"
APP_DIR="$SCRIPT_DIR/app"
BUILD_DIR="$SCRIPT_DIR/build"

# Check for Emscripten
if ! command -v emcc &>/dev/null; then
    echo "Emscripten not found. Install and activate the SDK, then source emsdk_env.sh:"
    echo "  https://emscripten.org/docs/getting_started/downloads.html"
    exit 1
fi

if [ $# -eq 0 ]; then
    echo "=== Building default WASM demo ==="
    mkdir -p "$BUILD_DIR"
    cd "$BUILD_DIR"
    emcmake cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
    emmake ninja
    echo ""
    echo "Done. Output: build/cyberfidget.js, build/cyberfidget.wasm"
    exit 0
fi

if [ $# -ne 2 ]; then
    echo "Usage: $0 [AppName.h AppName.cpp]"
    echo "  No args: build default demo"
    echo "  Two args: build custom app (files copied to wasm/app/)"
    exit 1
fi

H_FILE="$1"
CPP_FILE="$2"
if [ ! -f "$H_FILE" ]; then
    echo "Error: $H_FILE not found"
    exit 1
fi
if [ ! -f "$CPP_FILE" ]; then
    echo "Error: $CPP_FILE not found"
    exit 1
fi

# Base name from header (e.g. MyApp.h → MyApp)
BASE_H="${H_FILE##*/}"
APP_NAME="${BASE_H%.h}"

mkdir -p "$APP_DIR"
cp "$H_FILE" "$APP_DIR/$APP_NAME.h"
cp "$CPP_FILE" "$APP_DIR/$APP_NAME.cpp"

# app_include.h so main_wasm.cpp can include the custom app
echo "// Generated by build_wasm.sh - do not edit" > "$APP_DIR/app_include.h"
echo "#include \"App.h\"" >> "$APP_DIR/app_include.h"
echo "#include \"$APP_NAME.h\"" >> "$APP_DIR/app_include.h"

echo "=== Building custom WASM app: $APP_NAME ==="
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"
emcmake cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DWASM_APP=Custom -DCUSTOM_APP_NAME="$APP_NAME"
emmake ninja

echo ""
echo "Done. Output: build/cyberfidget.js, build/cyberfidget.wasm"
echo "Copy to the website's wasm/ directory or load the .wasm file in the emulator."
exit 0
